#FROM registry.access.redhat.com/ubi9/php-81
FROM php:8.2-fpm
USER root
RUN apt-get update && apt-get install vim -y
RUN mkdir app
COPY hello.php app/
EXPOSE 8080
RUN mkdir -p /var/www/html/
#RUN chown default /var/www/html/
RUN chmod 775 -R /var/www/html/
#CMD /usr/libexec/s2i/run